version: '3.8'

services:
  # Backend API service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/darwinfi
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_for_development
      - INJECTIVE_NETWORK=testnet
      - INJECTIVE_ENDPOINT=https://testnet.lcd.injective.network
      - INJECTIVE_WS_ENDPOINT=wss://testnet.api.injective.network
    depends_on:
      - mongo
      - redis
  
  # MongoDB service for database storage
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=darwinfi
  
  # Redis service for caching
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  # Frontend service (uncomment when ready to integrate with backend)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:5000/api
  #     - NODE_ENV=development
  #   depends_on:
  #     - backend

volumes:
  mongo-data:
  redis-data:

